version: '3'

networks:
    micropost-network:

services:
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8101:80"
        tty: true   
        environment:  
            - PMA_HOST=mysql
        networks:
            - micropost-network     
        restart: always                
        depends_on:
            - mysql     
    mysql:
        build: 
            context: ./docker/mysql      
            dockerfile: Dockerfile  
            args:
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}         
        tty: true
        cap_add:
            - SYS_NICE
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306" 
        networks:
            - micropost-network     
        restart: unless-stopped                                  
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/app
        working_dir: /app
        environment:
            - PHP_IDE_CONFIG=serverName=readit.loc
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=admin
            - POSTGRES_DB=readit_db   
            - REDIS_HOST="redis"
            - REDIS_PORT="6379"
            - XDEBUG_MODES=develop,debug
            - REMOTE_HOST=host.docker.internal
            - REMOTE_PORT=9003
            - IDE_KEY=docker
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - micropost-network         
        depends_on:
            - postgres  
            - redis  
    server:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - 8000:80
        volumes:
            - .:/app  
        networks:
            - micropost-network    
        extra_hosts:
            - host.docker.internal:host-gateway    
        depends_on:
            - php