<?php

namespace ContainerYxcRwQz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7UGzXxhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7UGzXxh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7UGzXxh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\FollowingController::follow' => ['privates', '.service_locator.qj6ZfC8', 'get_ServiceLocator_Qj6ZfC8Service', true],
            'App\\Controller\\FollowingController::unfollow' => ['privates', '.service_locator.x_hOScf', 'get_ServiceLocator_XHOScfService', true],
            'App\\Controller\\LikesController::like' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\LikesController::unlike' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\NotificationController::markAsRead' => ['privates', '.service_locator.qza7_MB', 'get_ServiceLocator_Qza7MBService', true],
            'App\\Controller\\PostController::editPost' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\PostController::removePost' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\PostController::userPosts' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\PostController::viewPost' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\FollowingController:follow' => ['privates', '.service_locator.qj6ZfC8', 'get_ServiceLocator_Qj6ZfC8Service', true],
            'App\\Controller\\FollowingController:unfollow' => ['privates', '.service_locator.x_hOScf', 'get_ServiceLocator_XHOScfService', true],
            'App\\Controller\\LikesController:like' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\LikesController:unlike' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\NotificationController:markAsRead' => ['privates', '.service_locator.qza7_MB', 'get_ServiceLocator_Qza7MBService', true],
            'App\\Controller\\PostController:editPost' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\PostController:removePost' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\PostController:userPosts' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\PostController:viewPost' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\FollowingController::follow' => '?',
            'App\\Controller\\FollowingController::unfollow' => '?',
            'App\\Controller\\LikesController::like' => '?',
            'App\\Controller\\LikesController::unlike' => '?',
            'App\\Controller\\NotificationController::markAsRead' => '?',
            'App\\Controller\\PostController::editPost' => '?',
            'App\\Controller\\PostController::removePost' => '?',
            'App\\Controller\\PostController::userPosts' => '?',
            'App\\Controller\\PostController::viewPost' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FollowingController:follow' => '?',
            'App\\Controller\\FollowingController:unfollow' => '?',
            'App\\Controller\\LikesController:like' => '?',
            'App\\Controller\\LikesController:unlike' => '?',
            'App\\Controller\\NotificationController:markAsRead' => '?',
            'App\\Controller\\PostController:editPost' => '?',
            'App\\Controller\\PostController:removePost' => '?',
            'App\\Controller\\PostController:userPosts' => '?',
            'App\\Controller\\PostController:viewPost' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
