<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'confirmationToken' => [parent::class, 'confirmationToken', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'followers' => [parent::class, 'followers', null],
        "\0".parent::class."\0".'following' => [parent::class, 'following', null],
        "\0".parent::class."\0".'fullName' => [parent::class, 'fullName', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isEnabled' => [parent::class, 'isEnabled', null],
        "\0".parent::class."\0".'likedPosts' => [parent::class, 'likedPosts', null],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'plainPassword' => [parent::class, 'plainPassword', null],
        "\0".parent::class."\0".'posts' => [parent::class, 'posts', null],
        "\0".parent::class."\0".'preferences' => [parent::class, 'preferences', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'confirmationToken' => [parent::class, 'confirmationToken', null],
        'email' => [parent::class, 'email', null],
        'followers' => [parent::class, 'followers', null],
        'following' => [parent::class, 'following', null],
        'fullName' => [parent::class, 'fullName', null],
        'id' => [parent::class, 'id', null],
        'isEnabled' => [parent::class, 'isEnabled', null],
        'likedPosts' => [parent::class, 'likedPosts', null],
        'notifications' => [parent::class, 'notifications', null],
        'password' => [parent::class, 'password', null],
        'plainPassword' => [parent::class, 'plainPassword', null],
        'posts' => [parent::class, 'posts', null],
        'preferences' => [parent::class, 'preferences', null],
        'roles' => [parent::class, 'roles', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            "\0".parent::class."\0".'plainPassword' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
