<?php

namespace ContainerSs1xSFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_MessageListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailer.message_listener' shared service.
     *
     * @return \Symfony\Component\Mailer\EventListener\MessageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/EventListener/MessageListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mime/Header/Headers.php';

        $a = new \Symfony\Component\Mime\Header\Headers();
        $a->addHeader('From', ['Micropost App <info@micropost.com>']);

        return $container->privates['mailer.message_listener'] = new \Symfony\Component\Mailer\EventListener\MessageListener($a);
    }
}
