<?php

namespace ContainerSs1xSFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Event\UserSubscriber' shared autowired service.
     *
     * @return \App\Event\UserSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Event/UserSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Mailer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/MailerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Event\\UserSubscriber'])) {
            return $container->privates['App\\Event\\UserSubscriber'];
        }
        $b = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\Event\\UserSubscriber'])) {
            return $container->privates['App\\Event\\UserSubscriber'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Event\\UserSubscriber'])) {
            return $container->privates['App\\Event\\UserSubscriber'];
        }
        $d = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Event\\UserSubscriber'])) {
            return $container->privates['App\\Event\\UserSubscriber'];
        }

        return $container->privates['App\\Event\\UserSubscriber'] = new \App\Event\UserSubscriber(new \App\Service\Mailer(new \Symfony\Component\Mailer\Mailer($a, $b, $c)), $d, 'en');
    }
}
