<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxcRwQz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxcRwQz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxcRwQz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxcRwQz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxcRwQz\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxcRwQz',
    'container.build_id' => '3b57cc26',
    'container.build_time' => 1693904548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxcRwQz');
